version: 2
jobs:
  publish:
    docker:
      - image: rishabhpoddar/supertokens_node_driver_testing
    steps:
      - checkout
      - run: ./gradlew clean build -x test bintrayUpload -PbintrayUser=supertokens -PbintrayKey=$BINTRAY_KEY -PdryRun=false
  test:
    docker: 
      - image: rishabhpoddar/supertokens_website_sdk_testing
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8b:c4:ca:c2:69:e7:fe:4e:fa:76:c1:66:d1:20:ad:f2"
      - checkout
      - run: (cd .circleci/ && ./doTests.sh)

workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test:
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/